-- 코드를 입력하세요
SELECT t.CATEGORY, SUM(t.TOTAL_SALES) FROM
(SELECT b.CATEGORY, bs.BOOK_ID, SUM(bs.SALES) AS TOTAL_SALES FROM BOOK_SALES bs 
INNER JOIN (SELECT BOOK_ID, CATEGORY FROM BOOK) b ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE >= '2022-01-01' AND bs.SALES_DATE <= '2022-01-31'
GROUP BY BOOK_ID) t
GROUP BY CATEGORY
ORDER BY CATEGORY;
